format_version = 2

[apps.KrakenApp]
category = 'public.app-category.graphics-design'
identifier = 'foundation.wabi.KrakenApp'
product = 'KrakenApp'
version = '1.0.0'

[apps.KrakenApp.plist]
commit = '$(COMMIT_HASH)'